'use client';
import { Download } from 'lucide-react';
import { Button } from '../ui/button';

export function DownloadSummaryButton({
  title,
  summaryText,
  createdAt,
}: {
  title: string;
  summaryText: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated on: ${new Date(createdAt).toLocaleDateString()}
    
${summaryText}
    
Generated by AI YT Summariser
`;

    const blob = new Blob([summaryContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      size="sm"
      onClick={handleDownload}
      style={{
        backgroundColor: '#fff1f2',
        color: '#e11d48',
        border: '1px solid #ffe4e6',
      }}
    >
      <Download
        style={{ height: '1rem', width: '1rem', marginRight: '0.25rem' }}
      />
      Download
    </Button>
  );
}
