'use client';
import { Download } from 'lucide-react';
import { Button } from '../ui/button';

export function DownloadSummaryButton({
  title,
  summaryText,
  createdAt,
}: {
  title: string;
  summaryText: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated on: ${new Date(createdAt).toLocaleDateString()}
    
${summaryText}
    
Generated by AI YT Summariser
`;

    const blob = new Blob([summaryContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      size={'sm'}
      className="h-8 hover:text-rose-700 hover:bg-rose-50 text-white bg-rose-500"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
