"use client";

import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { Button } from "../ui/button";
import {
  parseSection,
  parseEmojiPoint,
  parsePoint,
} from "@/utils/summary-helpers";

export function DownloadSummaryButton({
  title,
  summaryText,
  createdAt,
}: {
  title: string;
  summaryText: string;
  createdAt: string;
}) {
  const [isDownloading, setIsDownloading] = useState(false);

  const sections = summaryText
    .split("\n# ")
    .map((section) => section.trim())
    .filter(Boolean)
    .map(parseSection);

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const toPng = (await import("html-to-image")).toPng;
      const jsPDF = (await import("jspdf")).default;

      let pdf: any = null;
      const pdfWidth = 210; // A4 width in mm

      for (let i = 0; i < sections.length; i++) {
        const pageElement = document.getElementById(`printable-page-${i}`);
        if (!pageElement) continue;

        const imgData = await toPng(pageElement, {
          pixelRatio: 2,
          style: { transform: "scale(1)" },
        });

        const canvasWidth = 800;
        const canvasHeight = pageElement.offsetHeight;
        const scaledHeight = (canvasHeight * pdfWidth) / canvasWidth;

        // jsPDF auto-sorts dimensions. If height < width, we MUST use landscape orientation
        // to prevent it from swapping width and height and causing uneven page widths.
        const pageOrientation = scaledHeight < pdfWidth ? "l" : "p";

        if (!pdf) {
          pdf = new jsPDF({
            orientation: pageOrientation,
            unit: "mm",
            format: [pdfWidth, scaledHeight],
          });
        } else {
          pdf.addPage([pdfWidth, scaledHeight], pageOrientation);
        }

        pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, scaledHeight);
      }

      if (pdf) {
        pdf.save(`Summary-${title.replace(/[^a-z0-9]/gi, "_")}.pdf`);
      }
    } catch (error) {
      console.error("Error generating PDF:", error);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <>
      <Button
        size={"sm"}
        className="h-8 hover:text-rose-700 hover:bg-rose-50 text-white bg-rose-500"
        onClick={handleDownload}
        disabled={isDownloading}
      >
        {isDownloading ? (
          <Loader2 className="h-4 w-4 mr-1 animate-spin" />
        ) : (
          <Download className="h-4 w-4 mr-1" />
        )}
        {isDownloading ? "Generating PDF..." : "Download Summary"}
      </Button>

      {/* Hidden Printable Summary */}
      <div className="overflow-hidden h-0 w-0 absolute opacity-0 pointer-events-none">
        {sections.map((section, idx) => (
          <div
            key={idx}
            id={`printable-page-${idx}`}
            className="w-200 p-12 font-sans"
            style={{ backgroundColor: "#ffffff", color: "#111827" }}
          >
            {/* Header (Only on first page) */}
            {idx === 0 && (
              <div
                className="mb-10 border-b pb-6"
                style={{ borderBottomColor: "#e5e7eb" }}
              >
                <h1
                  className="text-4xl font-extrabold mb-4 leading-tight"
                  style={{ color: "#111827" }}
                >
                  {title}
                </h1>
                <div
                  className="flex flex-col gap-1 text-sm"
                  style={{ color: "#6b7280" }}
                >
                  <p>
                    Generated on: {new Date(createdAt).toLocaleDateString()}
                  </p>
                  <p
                    className="mt-2 font-semibold"
                    style={{ color: "#f43f5e" }}
                  >
                    Generated by AI YT Summariser
                  </p>
                </div>
              </div>
            )}

            {/* Content */}
            <div className="space-y-6">
              <h2
                className="text-2xl font-bold border-b pb-2"
                style={{ color: "#1f2937", borderBottomColor: "#ffe4e6" }}
              >
                {section.title}
              </h2>
              <div className="space-y-4">
                {section.points.map((point, pIdx) => {
                  const { isEmpty } = parsePoint(point);
                  if (isEmpty) return null;
                  const parsed = parseEmojiPoint(point);
                  const emoji = parsed?.emoji ?? "";
                  const text = parsed?.text ?? point.replace(/^[•]\s*/, "");

                  return (
                    <div
                      key={pIdx}
                      className="flex items-start gap-4 p-4 rounded-xl border"
                      style={{
                        backgroundColor: "rgba(249, 250, 251, 0.5)",
                        borderColor: "#f3f4f6",
                      }}
                    >
                      {emoji && (
                        <span className="text-xl shrink-0 pt-0.5">{emoji}</span>
                      )}
                      <p
                        className="text-lg leading-relaxed"
                        style={{ color: "#374151" }}
                      >
                        {text}
                      </p>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Footer (On every page) */}
            <div
              className="mt-12 pt-6 border-t flex justify-between items-center text-sm font-medium"
              style={{ borderTopColor: "#e5e7eb", color: "#9ca3af" }}
            >
              <p>Generated by AI YT Summariser</p>
              <p>
                Page {idx + 1} of {sections.length}
              </p>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
